---
tags:
- gobstones
- repetición
- simple
- MoverN
- PonerN
layout: input_right
editor: code
type: problem
extra_visible: true
teacher_info: ''
manual_evaluation: false
choices: []
name: Una línea heavy
